### ISSUE TITLE
Space as 1??????

### ISSUE THREAD

**Issue by proudloyaltier** [tiriassistant/tiri#1]
Neither me or any other user could be able to figure one as space out since it is not standard nor part of a keyboard.

Well, I think the space icon should be something like this??
<img width="32" alt="screen shot 2017-12-28 at 4 22 48 pm" src="https://user-images.githubusercontent.com/28576060/34423646-6835a240-ebeb-11e7-985d-fc86445a18f4.png">

You can copy this to use this icon [____]

Example code
`
<button onclick="predict(' ')">[____]</button>
`
Please commit these changes quickly

**Comment by tiriassistant** [comment]
Okay, added.

**Comment by proudloyaltier** [comment]
Good do the other one
