### ISSUE TITLE
No bubbles

### ISSUE THREAD

**Issue by proudloyaltier** [tiriassistant/tiri#2]
Does not look like the new tiri looks old fashioned , add bubbles

**Comment by proudloyaltier** [comment]
PLEASE

**Comment by proudloyaltier** [comment]
Also, I managed to make tiri for TI nspire!! DO this change

**Comment by tiriassistant** [comment]
Okay, bubbles will are being worked on now.

**Comment by proudloyaltier** [comment]
Good!! Use the same CSS

**Comment by proudloyaltier** [comment]
It isn't working TI

**Comment by tiriassistant** [comment]
Should be working now, I can use the TiMedia CSS if you want.

**Comment by proudloyaltier** [comment]
Bubbles don't show up on the Tiri Touch Mode at least, use the TiMedia CSS

**Comment by proudloyaltier** [comment]
# This is TI Please fix this now
> Bubbles don't show up on the Tiri Touch Mode at least, use the TiMedia CSS

**Comment by proudloyaltier** [comment]
Still don’t work android doesn’t either
